# Generated by Django 3.1.4 on 2021-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('filesize', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('belong', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Files',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaccount', models.CharField(max_length=100)),
                ('upassword', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=100)),
                ('ufiles', models.CharField(default='[]', max_length=1024)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
